# Basic Information 
title: Quoc H. Nguyen
position: Ph.D. Candidate
affiliation: University of South Florida
affiliation_link: https://www.usf.edu
affiliation_logo: ./assets/img/white-university-of-south-florida-usf-vector-logo-2022.svg
email: nguyenq29 (at) usf.edu

# Search Engine Optimization (SEO)
keywords: quoc nguyen, quoc h nguyen, quoc usf
canonical: https://quocnh.github.io/
description: Quoc H. Nguyen is a Ph.D candidate at University of South Florida. His research lies in federated learning, internet of medical things and image generation.
theme: minima
# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=yikSJwMAAAAJ&hl=en
cv_link: ./assets/Quoc_Industry_Resume_03132024.pdf
github_link: https://github.com/quocnh/
linkedin: https://www.linkedin.com/in/quocnh/
# twitter: https://twitter.com/

# Images 
avatar: ./assets/img/mark_photo.jpg
favicon: ./assets/img/South_Florida_Bulls_logo_PNG3.png.png
favicon_dark: ./assets/img/South_Florida_Bulls_logo_PNG3.png.png

# Footnotes
# footnote: Feel free to use my website's source code.
footnote_link: https://quocnh.github.io/
paginate: 5
# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8



# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
